# Generated by Django 5.2.1 on 2025-10-25 16:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBETransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='CBE transaction ID')),
                ('merchant_id', models.CharField(max_length=50, verbose_name='merchant ID')),
                ('terminal_id', models.CharField(max_length=50, verbose_name='terminal ID')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='invoice number')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='initiated', max_length=20, verbose_name='status')),
                ('cbe_response', models.JSONField(blank=True, null=True, verbose_name='CBE response')),
                ('callback_received', models.BooleanField(default=False, verbose_name='callback received')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'CBE transaction',
                'verbose_name_plural': 'CBE transactions',
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('cbe', 'CBE Birr'), ('telebirr', 'TeleBirr')], max_length=20, unique=True, verbose_name='gateway name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('test_mode', models.BooleanField(default=True, verbose_name='test mode')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API key')),
                ('api_secret', models.CharField(blank=True, max_length=255, verbose_name='API secret')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='webhook secret')),
                ('additional_config', models.JSONField(blank=True, null=True, verbose_name='additional configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'payment gateway',
                'verbose_name_plural': 'payment gateways',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='refund ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('reason', models.TextField(verbose_name='reason')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('gateway_refund_id', models.CharField(blank=True, max_length=100, verbose_name='gateway refund ID')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='gateway response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
            ],
            options={
                'verbose_name': 'refund',
                'verbose_name_plural': 'refunds',
            },
        ),
        migrations.CreateModel(
            name='TeleBirrTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='TeleBirr transaction ID')),
                ('short_code', models.CharField(max_length=20, verbose_name='short code')),
                ('app_key', models.CharField(blank=True, max_length=100, verbose_name='app key')),
                ('app_secret', models.CharField(blank=True, max_length=100, verbose_name='app secret')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='initiated', max_length=20, verbose_name='status')),
                ('telebirr_response', models.JSONField(blank=True, null=True, verbose_name='TeleBirr response')),
                ('ussd_code', models.CharField(blank=True, max_length=50, verbose_name='USSD code')),
                ('qr_code_url', models.URLField(blank=True, verbose_name='QR code URL')),
                ('callback_received', models.BooleanField(default=False, verbose_name='callback received')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'TeleBirr transaction',
                'verbose_name_plural': 'TeleBirr transactions',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='payment ID')),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('cbe', 'CBE Birr'), ('telebirr', 'TeleBirr'), ('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'Cash on Delivery')], max_length=20, verbose_name='payment method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20, verbose_name='status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='ETB', max_length=3, verbose_name='currency')),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100, verbose_name='gateway payment ID')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='gateway response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='failed at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
