# Generated by Django 5.2.1 on 2025-10-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'Cash on Delivery'), ('cbe', 'CBE Birr'), ('telebirr', 'TeleBirr')], max_length=20, verbose_name='payment method'),
        ),
    ]
